# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_core.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlayerMainWindow(object):
    def setupUi(self, PlayerMainWindow):
        PlayerMainWindow.setObjectName("PlayerMainWindow")
        PlayerMainWindow.resize(998, 584)
        self.centralwidget = QtWidgets.QWidget(PlayerMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxRtspStream = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxRtspStream.setGeometry(QtCore.QRect(250, 20, 741, 541))
        self.groupBoxRtspStream.setFlat(False)
        self.groupBoxRtspStream.setObjectName("groupBoxRtspStream")
        self.lineEditRtspAddress = QtWidgets.QLineEdit(self.groupBoxRtspStream)
        self.lineEditRtspAddress.setGeometry(QtCore.QRect(90, 20, 640, 20))
        self.lineEditRtspAddress.setObjectName("lineEditRtspAddress")
        self.videoFrame = QtWidgets.QFrame(self.groupBoxRtspStream)
        self.videoFrame.setGeometry(QtCore.QRect(10, 50, 720, 480))
        self.videoFrame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.videoFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.videoFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.videoFrame.setObjectName("videoFrame")
        self.pushButtonControlStream = QtWidgets.QPushButton(self.groupBoxRtspStream)
        self.pushButtonControlStream.setGeometry(QtCore.QRect(10, 15, 75, 30))
        self.pushButtonControlStream.setObjectName("pushButtonControlStream")
        self.groupBoxTCP = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxTCP.setGeometry(QtCore.QRect(20, 20, 221, 81))
        self.groupBoxTCP.setObjectName("groupBoxTCP")
        self.labelIP = QtWidgets.QLabel(self.groupBoxTCP)
        self.labelIP.setGeometry(QtCore.QRect(10, 20, 30, 20))
        self.labelIP.setObjectName("labelIP")
        self.labelPort = QtWidgets.QLabel(self.groupBoxTCP)
        self.labelPort.setGeometry(QtCore.QRect(10, 50, 30, 20))
        self.labelPort.setObjectName("labelPort")
        self.lineEditIPAddr = QtWidgets.QLineEdit(self.groupBoxTCP)
        self.lineEditIPAddr.setGeometry(QtCore.QRect(50, 20, 160, 20))
        self.lineEditIPAddr.setObjectName("lineEditIPAddr")
        self.lineEditIPPort = QtWidgets.QLineEdit(self.groupBoxTCP)
        self.lineEditIPPort.setGeometry(QtCore.QRect(50, 50, 70, 20))
        self.lineEditIPPort.setObjectName("lineEditIPPort")
        self.pushButtonConnect = QtWidgets.QPushButton(self.groupBoxTCP)
        self.pushButtonConnect.setGeometry(QtCore.QRect(130, 50, 80, 20))
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.groupBoxConnectLog = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxConnectLog.setGeometry(QtCore.QRect(20, 450, 221, 111))
        self.groupBoxConnectLog.setObjectName("groupBoxConnectLog")
        self.textBrowserConnectLog = QtWidgets.QTextBrowser(self.groupBoxConnectLog)
        self.textBrowserConnectLog.setGeometry(QtCore.QRect(10, 20, 200, 80))
        self.textBrowserConnectLog.setObjectName("textBrowserConnectLog")
        PlayerMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PlayerMainWindow)
        self.statusbar.setObjectName("statusbar")
        PlayerMainWindow.setStatusBar(self.statusbar)
        self.actionPlayer = QtWidgets.QAction(PlayerMainWindow)
        self.actionPlayer.setObjectName("actionPlayer")

        self.retranslateUi(PlayerMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PlayerMainWindow)

    def retranslateUi(self, PlayerMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PlayerMainWindow.setWindowTitle(_translate("PlayerMainWindow", "Rtsp Stream Player"))
        self.groupBoxRtspStream.setTitle(_translate("PlayerMainWindow", "Rtsp Stream"))
        self.lineEditRtspAddress.setText(_translate("PlayerMainWindow", "rtsp://192.168.161.208/mystream"))
        self.pushButtonControlStream.setText(_translate("PlayerMainWindow", "Play"))
        self.groupBoxTCP.setTitle(_translate("PlayerMainWindow", "TCP"))
        self.labelIP.setText(_translate("PlayerMainWindow", "IP:"))
        self.labelPort.setText(_translate("PlayerMainWindow", "port:"))
        self.lineEditIPAddr.setText(_translate("PlayerMainWindow", "127.0.0.1"))
        self.lineEditIPPort.setText(_translate("PlayerMainWindow", "8080"))
        self.pushButtonConnect.setText(_translate("PlayerMainWindow", "Connect"))
        self.groupBoxConnectLog.setTitle(_translate("PlayerMainWindow", "Connect Log"))
        self.actionPlayer.setText(_translate("PlayerMainWindow", "Player"))
